variables:
  PYTHON_VERSION: python
  STAGING: y

stages:
  - install
  - test
  - deploy_prod

.artifacts: &artifacts
  artifacts:
    paths:
      - .env/

.image_test: &image_test
  image: paradoxxxzero/python-node-yarn-postgresql:latest

install:
  stage: install
  <<: *image_test
  script:
    - make install
  <<: *artifacts

lint:
  stage: test
  <<: *image_test
  script:
    - make lint
  dependencies:
    - install

test:
  stage: test
  <<: *image_test
  script:
    - make check
  dependencies:
    - install

.image: &image_deploy_jobs
  image: debian:latest

deploy_prod:
  <<: *image_deploy_jobs
  stage: deploy_prod
  before_script:
    - 'apt-get update && apt-get install -y wget'
  script:
    - 'set -e'
    - 'output_file=/tmp/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.log'
    - 'parameters="{\"job_id\":\"$CI_JOB_ID\", \"token\":\"$TOKEN\", \"build_stage\":\"$CI_JOB_STAGE\", \"project_name\":\"$CI_PROJECT_NAME\", \"branch\":\"$CI_COMMIT_REF_NAME\"}"'
    - 'swget="wget --no-verbose --content-on-error -O-"'
    - '$swget --header="Content-Type:application/json" --post-data="""$parameters""" $JUNKRAT | tee $output_file && [[ $(tail -n1 $output_file) == "Success" ]]'
    - '$swget https://sherlog.kozea.fr/graph/Anne-Laure/ping6'
  dependencies: []
  only:
    - master
