"""Add indexes on server_name and host columns

Revision ID: 3035e7fed632
Revises: 0d3345bcc6c2
Create Date: 2018-02-16 16:47:46.715068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3035e7fed632'
down_revision = '0d3345bcc6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_log_host'), 'log', ['host'], unique=False)
    op.create_index(op.f('ix_log_server_name'), 'log', ['server_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_server_name'), table_name='log')
    op.drop_index(op.f('ix_log_host'), table_name='log')
    # ### end Alembic commands ###
